# Generated by Django 4.2.2 on 2023-08-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='budget',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
