# Generated by Django 4.2.2 on 2023-08-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='id',
        ),
        migrations.AddField(
            model_name='budget',
            name='CODTYPAC',
            field=models.CharField(default='AA', max_length=3),
        ),
        migrations.AddField(
            model_name='budget',
            name='IDEIMPST',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='LIBACTGE',
            field=models.CharField(default='no libelle', max_length=50),
        ),
        migrations.AddField(
            model_name='budget',
            name='MOISSOLD',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
