# Generated by Django 4.2.2 on 2023-08-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0002_purchase_budget_alter_purchase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='MONTSTRU',
        ),
        migrations.AddField(
            model_name='itempurchase',
            name='MONTSTRU',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='itempurchase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
