# Generated by Django 4.2.2 on 2023-08-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0002_remove_budget_id_budget_codtypac_budget_ideimpst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(default='no username', max_length=50)),
                ('email', models.CharField(default='no email', max_length=50)),
                ('password', models.CharField(default='no password', max_length=50)),
            ],
        ),
    ]
