# Generated by Django 4.2.2 on 2023-08-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0003_remove_purchase_montstru_itempurchase_montstru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempurchase',
            name='MONTSTRU',
        ),
        migrations.AddField(
            model_name='item',
            name='MONTSTRU',
            field=models.FloatField(default=0),
        ),
    ]
