# Generated by Django 4.2.2 on 2023-08-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0004_user_firstname_user_lastname_user_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
