# Generated by Django 4.2.2 on 2023-08-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0005_remove_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='UserId',
            field=models.IntegerField(default=0),
        ),
    ]
