# Generated by Django 4.2.2 on 2023-08-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0006_purchase_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='total',
        ),
    ]
