# Generated by Django 4.2.2 on 2023-08-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0006_budget_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='UserId',
        ),
        migrations.AddField(
            model_name='budget',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BudgetPRed.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='pathPhoto',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
    ]
