# Generated by Django 4.2.2 on 2023-08-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0007_remove_purchase_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempurchase',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
