# Generated by Django 4.2.2 on 2023-08-05 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0007_remove_budget_userid_budget_user_user_pathphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BudgetPRed.user'),
        ),
    ]
