# Generated by Django 4.2.2 on 2023-08-23 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0008_itempurchase_is_purchased'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('savings', models.FloatField(default=0)),
                ('budget', models.FloatField(default=0)),
                ('spendings', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BudgetPRed.user')),
            ],
        ),
    ]
