# Generated by Django 4.2.2 on 2023-08-05 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0008_alter_budget_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetPRed.user'),
        ),
    ]
