# Generated by Django 4.2.2 on 2023-08-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0009_alter_budget_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budgetPhoto',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/items'),
        ),
    ]
