# Generated by Django 4.2.2 on 2023-08-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0009_monthlybudget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='month_budget',
        ),
    ]
