# Generated by Django 4.2.2 on 2023-08-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0010_budget_budgetphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budgetPhoto',
            new_name='budgetphoto',
        ),
    ]
