# Generated by Django 4.2.2 on 2023-08-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0011_rename_budgetphoto_budget_budgetphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='CODTYPAC',
            field=models.CharField(default='no code', max_length=50),
        ),
    ]
