# Generated by Django 4.2.2 on 2023-08-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0012_alter_budget_codtypac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budgetphoto',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='static/items'),
        ),
    ]
