# Generated by Django 4.2.2 on 2023-08-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0013_rename_devise_user_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='needs_new_form',
            field=models.BooleanField(default=True),
        ),
    ]
