# Generated by Django 4.2.2 on 2023-08-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0013_alter_budget_budgetphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pathPhoto',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='static/images'),
        ),
    ]
