# Generated by Django 4.2.2 on 2023-08-09 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0014_alter_user_pathphoto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Budget',
            new_name='Item',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default='2021-01-01')),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetPRed.item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetPRed.user')),
            ],
        ),
    ]
