# Generated by Django 4.2.2 on 2023-08-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0015_rename_budget_item_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='User',
        ),
    ]
