# Generated by Django 4.2.2 on 2023-08-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0016_remove_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='date',
            new_name='MOISSOLD',
        ),
        migrations.RemoveField(
            model_name='item',
            name='MOISSOLD',
        ),
    ]
