# Generated by Django 4.2.2 on 2023-08-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0017_rename_date_purchase_moissold_remove_item_moissold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Budgets',
        ),
        migrations.RemoveField(
            model_name='item',
            name='MONTRAPP',
        ),
        migrations.RemoveField(
            model_name='item',
            name='MONTSTRU',
        ),
        migrations.AddField(
            model_name='purchase',
            name='Budgets',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='MONTRAPP',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='MONTSTRU',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='month_budget',
            field=models.FloatField(default=0),
        ),
    ]
