# Generated by Django 4.2.2 on 2023-08-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0018_remove_item_budgets_remove_item_montrapp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='Budgets',
        ),
    ]
