# Generated by Django 4.2.2 on 2023-08-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0019_remove_purchase_budgets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='budget',
            new_name='item',
        ),
    ]
