# Generated by Django 4.2.2 on 2023-08-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0020_rename_budget_purchase_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='TOTAL',
            field=models.FloatField(default=0),
        ),
    ]
