# Generated by Django 4.2.2 on 2023-08-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0022_rename_total_purchase_budgets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='Budgets',
        ),
    ]
