# Generated by Django 4.2.2 on 2023-08-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetPRed', '0023_remove_purchase_budgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categorie',
            field=models.CharField(default='no categorie', max_length=50),
        ),
    ]
